FROM python:3.11
# RUN apt-get update && apt-get install -y ffmpeg

# Install necessary dependencies
RUN apt-get update && apt-get install -y \
    curl \
    ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Allow statements and log messages to immediately appear in the
ENV PYTHONUNBUFFERED True
# Copy application dependency manifests to the container image.
# Copying this separately prevents re-running pip install on eve.
COPY requirements.txt ./
# Install production dependencies.
RUN pip install -r requirements.txt
# Copy local code to the container image.
ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . ./
EXPOSE 9000
ENV PORT 9000
ENV HOST 0.0.0.0
CMD exec uvicorn server:app --port 9000 --host 0.0.0.0